// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/docusign-navigator/AgreementsList.tsx": () => import("../components/mockups/docusign-navigator/AgreementsList.tsx")
};
